### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by noorsyyad** [MadeWithCards/AdaptiveCardsStudio#2] opened 2021-02-08 12:35 UTC
- Issue Type: `Performance`
- Extension Name: `adaptivecardsstudiobeta`
- Extension Version: `1.0.5`
- OS Version: `Windows_NT x64 10.0.21301`
- VSCode version: `1.53.0-insider`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by noorsyyad** [comment] 2021-02-08 12:39
[madewithcardsio.adaptivecardsstudiobeta-unresponsive.cpuprofile.txt](https://github.com/MadeWithCards/AdaptiveCardsStudio/files/5943704/madewithcardsio.adaptivecardsstudiobeta-unresponsive.cpuprofile.txt)

**Comment by DeeJayTC** [comment] 2021-02-13 14:24
Hey @noorsyyad thanks for that. I'll have a look. 
Are you sure its caused by the Card Studio extension? I did not see anything myself by now but surely i'll investigate!

Thanks!

**Comment by DeeJayTC** [comment] 2021-02-13 14:26
Looks like its actually related to the AdaptiveExpression package the Extension is using, might be one for @matthidinger 's Team but i'll follow up.

**Comment by DeeJayTC** [comment] 2021-03-25 07:46
Hey @noorsyyad we tried to have a deeper look at what would cause this and couldn't really find anything. Can you give us a litle bit more information, maybe the card template you where using and how you created that profile? I can not reproduce that issue on my machine right now.

**Comment by DeeJayTC** [comment] 2021-05-03 22:02
I'm closing this, feel free to re-open. We can't reproduce the issue and without further help we can't do anything here.

**Closed by DeeJayTC** 2021-05-03 22:02 UTC
Labels: bug
